gpt-3.5-turbo-0613:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-3.5-turbo-0613"
        body:
            model: "gpt-3.5-turbo-0613"
            max_tokens: 512

gpt-o4-mini:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-o4-mini"
        url: <url>/openai/deployments/o4-mini/chat/completions
        body:
            model: "o4-mini"
            max_completion_tokens: 512

gpt-4o:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-4o"
        url: <url>/openai/deployments/gpt-4o/chat/completions
        body:
            model: "gpt-4o"
            max_tokens: 512
            temperature: 0

gpt-o1:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-o1"
        url: <url>/openai/deployments/o1/chat/completions
        body:
            model: "o1"
            max_completion_tokens: 512

qwq-32b:
    import: "./qwq.yaml"
    parameters:
        name: "qwq-32b"
        body:
            model: "qwq-32b"
            max_tokens: 512


text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512

