module: src.client.agents.qwq_agent.QWQAgent
parameters:
    name: "qwq-32b"
    api_args:
      model: "qwq-32b"
      base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      temperature: 0.7
      max_tokens: 512