import: definition.yaml

concurrency:
  task:
    dbbench-std: 5
    os-std: 5
    alfworld-std: 5
    webshop-std: 5
    alfworld-dev: 5
  agent:
    # gpt-3.5-turbo-0613: 5
    qwq-32b: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      # - gpt-3.5-turbo-0613
      - qwq-32b
    task:
      # - dbbench-std
      # - os-std
      # alfworld-dev
      - alfworld-std
      # - webshop-std
output: "outputs/{TIMESTAMP}"
